### PR TITLE
add first components of stat/hypo test submodule

### PR DESCRIPTION
**Pull request by marinang**
This PR includes the creation of `hypotests` submodule with two files

- `parameters.py` with `POI` class for parameter of interest definition
- `basecalculator.py` with `BaseCalculator` base class for calculators

This PR just contains basic classes of what I would like to implement in the future such as a frequentist calculator and an asymptotic calculator (same as https://github.com/marinang/lauztat/tree/master/lauztat/calculators) which will be subclass of `BaseCalculator` as I was explaining in #1.
Those subclasses should define the following methods:

- `_pvalue`
- `_expected_pvalue`
- `_expected_poi`

The fitting backend is `zfit` which has a lot of goodies for this project.

### CODE REVIEW

**Comment by marinang** [comment]
Now this pull request doesn't depend on zfit anymore, but on it's API.

**Comment by marinang** [comment]
Happy to be reviewed :) !

**Comment by eduardo-rodrigues** [comment]
I will have a look this week, @marinang. Apologies for the long silence!

**Comment by marinang** [comment]
@eduardo-rodrigues Thanks. I agree I will put more documentation and examples in the following PR.

**Pull request merged**
